name: asset_reliability
version: "1.0.0"
config-version: 2
profile: asset_reliability

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

flags:
  send_anonymous_usage_stats: false

models:
  asset_reliability:
    staging:
      +materialized: view
    marts:
      +materialized: table
